/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isak.ahlberg
 */
import java.awt.Graphics;
public class GraphArea extends javax.swing.JPanel {
    private priorityGraphics priorityGraphic = new priorityGraphics(0); // Creates the graphical class with priority 0.
    /**
     * Creates new form ritYta
     */
    public GraphArea() {
        initComponents();
    }
    // Prints the graphical class
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        priorityGraphic.paint(g);
    }
    // Used to set the priority and repaints the class. Used in jPanel so it gains access to the graphical class.
    public void setPriority(int priority){
        priorityGraphic.setpriority(priority);
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
