/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isak
 */
import java.util.Random;
import javax.swing.JOptionPane;

public class jPanel extends javax.swing.JPanel {

    /**
     * Creates new form jPanel
     */
    public jPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        issueDialog = new javax.swing.JDialog();
        cancelBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescriptionArea = new javax.swing.JTextArea();
        typeCombo = new javax.swing.JComboBox<>();
        priorityCombo = new javax.swing.JComboBox<>();
        warningDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        dialogBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descPreview = new javax.swing.JTextArea();
        fixedToggle = new javax.swing.JCheckBox();
        removeBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ritYta1 = new GraphArea();
        sortComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        issueDialog.setMinimumSize(new java.awt.Dimension(491, 368));

        cancelBtn.setText("Cancel");
        cancelBtn.setToolTipText("");

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Type:");

        jLabel3.setText("Priority: ");

        jLabel4.setText("Description: ");

        DescriptionArea.setColumns(20);
        DescriptionArea.setRows(5);
        jScrollPane2.setViewportView(DescriptionArea);

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Web exploit", "bug", "weak encryption", "DOS" }));

        priorityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout issueDialogLayout = new javax.swing.GroupLayout(issueDialog.getContentPane());
        issueDialog.getContentPane().setLayout(issueDialogLayout);
        issueDialogLayout.setHorizontalGroup(
            issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issueDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn))
                    .addGroup(issueDialogLayout.createSequentialGroup()
                        .addGroup(issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(issueDialogLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(issueDialogLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        issueDialogLayout.setVerticalGroup(
            issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issueDialogLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priorityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issueDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(issueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn)
                            .addComponent(addBtn)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );

        warningDialog.setIconImage(null);
        warningDialog.setType(java.awt.Window.Type.UTILITY);

        javax.swing.GroupLayout warningDialogLayout = new javax.swing.GroupLayout(warningDialog.getContentPane());
        warningDialog.getContentPane().setLayout(warningDialogLayout);
        warningDialogLayout.setHorizontalGroup(
            warningDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        warningDialogLayout.setVerticalGroup(
            warningDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(835, 450));

        issueArea.setEditable(false);
        issueArea.setColumns(20);
        issueArea.setRows(5);
        jScrollPane1.setViewportView(issueArea);

        jLabel1.setText("Choose Issue:");

        searchBtn.setText("Go");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        dialogBtn.setText("Add Issue");
        dialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        descPreview.setEditable(false);
        descPreview.setColumns(20);
        descPreview.setRows(5);
        jScrollPane3.setViewportView(descPreview);

        fixedToggle.setText("Fixed");
        fixedToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedToggleActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Priority:");

        javax.swing.GroupLayout ritYta1Layout = new javax.swing.GroupLayout(ritYta1);
        ritYta1.setLayout(ritYta1Layout);
        ritYta1Layout.setHorizontalGroup(
            ritYta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        ritYta1Layout.setVerticalGroup(
            ritYta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ritYta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fixedToggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ritYta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fixedToggle))
                    .addComponent(removeBtn))
                .addContainerGap())
        );

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID 0-9", "ID  9-0", "Prioritet 0-9", "Prioritet 9-0" }));
        sortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Sort:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dialogBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 147, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dialogBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        // Sets the description preview to ""
        this.descPreview.setText("");
        // Sets the search term for use if the remove and setFixed methods
        this.search = this.searchField.getText();
        // Tries to search, exception thrown if search term is invalid.
        try {
            int i = search(this.search);
            this.descPreview.setText(this.Issues.get(i).getDescription());
            this.fixedToggle.setSelected(this.Issues.get(i).getFixed()); // Sets the check box to toggles or untoggled based on if the issue is fixed or not
            this.ritYta1.setPriority(this.Issues.get(i).getPriorityLevel()); // sets the priority level for the graphical class.
            this.searchField.setText("");
        } catch (Exception e) {
            ErrorMessage("Vändligen skriv in ett korrekt ID.");
            this.searchField.setText("");
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void dialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogBtnActionPerformed
        // TODO add your handling code here:
        issueDialog.setVisible(true);
    }//GEN-LAST:event_dialogBtnActionPerformed
    private void ErrorMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Felmeddelande", JOptionPane.ERROR_MESSAGE);
    }
    // Adds an issue to the list
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String description = this.DescriptionArea.getText(); // Gets the description.
        String type = this.typeCombo.getItemAt(this.typeCombo.getSelectedIndex()); // Gets the type of issue
        int priority = Integer.valueOf(this.priorityCombo.getItemAt(this.priorityCombo.getSelectedIndex())); // Gets the priority of the issue
        // Creates a new Issue based on the description, type, priority and auto generated ID
        Issue newIssue = new Issue(generateID(), description, type, priority); 
        Issues.addIssue(newIssue); // Adds the new issue to the list
        this.DescriptionArea.setText(""); // resets the description text area
        this.issueDialog.setVisible(false); // Hides the add issue dialog
        sort(); // sorts the issues ArrayList based on selected sorting mode
        updateIssueTextArea(); // Updates the visual representation of the issue list. 
    }//GEN-LAST:event_addBtnActionPerformed

    private void sortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortComboBoxActionPerformed
        // TODO add your handling code here:
        // Changes sorting mode and sorts the issues ArrayList
        sort();
        updateIssueTextArea();
    }//GEN-LAST:event_sortComboBoxActionPerformed
    // Sort the list of issues based on what sort mode is selected.
    private void sort() {
        switch (this.sortComboBox.getSelectedIndex()) {
            case 0:
                this.Issues.sortByNameLowHigh();
                break;
            case 1:
                this.Issues.sortByNameHighLow();
                break;
            case 2:
                this.Issues.sortByPriorityLowHigh();
                break;
            case 3:
                this.Issues.sortByPriorityHighLow();
                break;
            default:
                break;
        }
        updateIssueTextArea();
    }
    private void fixedToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedToggleActionPerformed
        // TODO add your handling code here:
        // Try-Catch for if the search bar is empty or has an invalid search term.
        try {
            // Searches for this.search so it can't be deleted.
            int i = search(this.search);
            this.Issues.get(i).setFixed(this.fixedToggle.isSelected());
            updateIssueTextArea();
        } catch (Exception e) {
            ErrorMessage("Vändligen skriv in ett korrekt ID.");
            this.fixedToggle.setSelected(!this.fixedToggle.isSelected()); // If an exception is thrown is reverts the toggle switch.
        }
    }//GEN-LAST:event_fixedToggleActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnActionPerformed

    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseClicked
        // TODO add your handling code here:
        // Removes the specified issue. Exception thrown if ID is invalid.
        try {
            int i = search(this.search);
            this.Issues.remove(i);
            this.descPreview.setText("");
            this.searchField.setText("");
            updateIssueTextArea();
        } catch (Exception e) {
            ErrorMessage("Vändligen skriv in ett korrekt ID.");
        }
    }//GEN-LAST:event_removeBtnMouseClicked
    // Generates an ID.
    private String generateID() {
        int id = rnd.nextInt((999 - 100)) + 100;
        /*
        If the generated id is a duplicate it generates a new ID, self-calling.
        */
        if(search(Integer.toString(id)) == -1){
            return Integer.toString(id);
        } else{
            System.out.println(id);
            generateID();
        }
        return null; //Just so it doesn't complain about missing return statement.
    }
    // Searches for an ID in the Issues ArrayList.
    private int search(String str) {
        for (int i = 0; i < Issues.size(); i++) {
            if (this.Issues.get(i).getID().equals(str)) {
                return i;
            }
        }
        return -1;
    }
    // Updates the visual representation of the Issues ArrayList. It's used when sorting and adding an issue.
    // It updates the IssueTextArea.
    public void updateIssueTextArea() {
        this.issueArea.setText("");
        for (int i = 0; i < this.Issues.size(); i++) {
            this.issueArea.setText(this.issueArea.getText() + this.Issues.get(i).toString() + "\n");
        }
    }
    // Variable declaration - do modify
    private Random rnd = new Random();
    private IssueList Issues = new IssueList();
    private String search;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DescriptionArea;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea descPreview;
    private javax.swing.JButton dialogBtn;
    private javax.swing.JCheckBox fixedToggle;
    private javax.swing.JTextArea issueArea;
    private javax.swing.JDialog issueDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> priorityCombo;
    private javax.swing.JButton removeBtn;
    private GraphArea ritYta1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> sortComboBox;
    private javax.swing.JComboBox<String> typeCombo;
    private javax.swing.JDialog warningDialog;
    // End of variables declaration//GEN-END:variables
}
